// <auto-generated />
using LogensAPI.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace LogensAPI.Migrations
{
    [DbContext(typeof(LoginDbContext)), Migration("20221114075218_initial create")]
    public class initialcreateBase1
    {
    }
}